---
version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:4.6.1-1-ce
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://$PASSBOLT_DOMAIN
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "$MYSQL_PASSWORD"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_DEFAULT_FROM_NAME: "Passbolt"
      EMAIL_DEFAULT_FROM: "passbolt@$PASSBOLT_DOMAIN"
      EMAIL_TRANSPORT_DEFAULT_HOST: "exim"
      EMAIL_TRANSPORT_DEFAULT_PORT: "25"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/letsencrypt/live/$PASSBOLT_DOMAIN/fullchain.pem:/etc/ssl/certs/certificate.crt:ro
      - /etc/letsencrypt/live/$PASSBOLT_DOMAIN/privkey.pem:/etc/ssl/certs/certificate.key:ro
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 80:80
      - 443:443
  exim:
    image: tianon/exim4
    restart: always
    hostname: '$PASSBOLT_DOMAIN'
    ports:
      - '25:25'

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
